# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Uncomment this to still load settings configured via autoconfig.yml
config.load_autoconfig()

config.set('editor.command', ['nvim-qt', '{file}'])
config.set('hints.chars', 'arstdhneio')
config.set('scrolling.smooth', True)

config.bind('n', 'scroll down')
config.bind('e', 'scroll up')
config.bind('i', 'scroll right')

config.bind('H', 'tab-prev')
config.bind('I', 'tab-next')
config.bind('<Ctrl-o>', 'back')
config.bind('<Ctrl-i>', 'forward')

config.bind('gt', 'tab-next')
config.bind('gT', 'tab-prev')

config.bind('N', 'scroll down', mode='caret')
config.bind('E', 'scroll up', mode='caret')
config.bind('I', 'scroll right', mode='caret')
config.bind('n', 'move-to-next-line', mode='caret')
config.bind('e', 'move-to-prev-line', mode='caret')
config.bind('i', 'move-to-next-char', mode='caret')
