[user]
name = "Adam Lloyd"
email = "adam@alloy-d.net"

[fix.tools.deno-ts]
command = ["deno", "fmt", "-", "--ext", "ts"]
patterns = ["glob:'**/*.ts'"]

[fix.tools.deno-css]
command = ["deno", "fmt", "-", "--ext", "css"]
patterns = ["glob:'**/*.css'"]

[fix.tools.deno-jsonc]
command = ["deno", "fmt", "-", "--ext", "jsonc"]
patterns = ["glob:'**/*.json'", "glob:'**/*.jsonc'"]

[fix.tools.deno-svelte]
command = ["deno", "fmt", "-", "--unstable-component", "--ext", "svelte"]
patterns = ["glob:'**/*.svelte'"]

# [fix.tools.deno-svg]
# command = ["deno", "fmt", "-", "--unstable-component", "--ext", "svg"]
# patterns = ["glob:'**/*.svg'"]

[fix.tools.swift-format]
command = ["swift-format", "format", "-"]
patterns = ["glob:'**/*.swift'"]

### GPG signing setup
#
# Here's the deal: firstly, it seems like signing.sign-all does not have
# any effect on the GPG backend at the moment (jj 0.26.0), and it always
# tries to sign every jj operation.  Since I have to touch a hardware
# key every time I sign something, this is *hugely* inconvenient.
#
# However, even if signing on push did work correctly, I'm not sure
# security juice is worth the squeeze: if I'm blindly tapping a key to
# sign a batch of commits, is that meaningfully more secure than using
# an SSH key that doesn't require interaction at the time of signing?
# I think not; I think it's just more inconvenient and causes more havoc
# in the commit metadata (since the committer date changes when the
# commit is signed).
#
# I think the nature of how jj works just is not going to play nicely
# with attended commit signing, so this seems like a reasonable
# compromise.  The SSH key is still somewhat tied to my session via the
# agent, so it's still somewhat better than not signing at all.
#
# [git]
# sign-on-push = true
#
# [signing]
# sign-all = false
# behavior = "drop"
#
# backend = "gpg"
# key = "CE6763347250996E"

### SSH signing setup
[signing]
behavior = "own"

backend = "ssh"
key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPl55gX1G01agzhO2IjR5ph00FnGov/ewlghcdm5RDu5 SSH commit signing"

# Seems like this must be an absolute path, and ~ is not expanded:
backends.ssh.allowed-signers = "/Users/awl/.ssh/allowed_signers"

[template-aliases]
# I changed this when using git.sign-on-push.  That caused every commit
# to have the same timestamp, and I thought that was unhelpful and
# weird.  Now that I've changed my signing setup, I'll give the defaults
# another try.
#
#'commit_timestamp(commit)' = 'commit.author().timestamp()'

[ui]
diff-editor = ":builtin"
show-cryptographic-signatures = true
default-command = "log"
