# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

import os

config.load_autoconfig()

config.set('editor.command', ['nvim-qt', '{file}'])
config.set('fonts.default_family', 'Iosevka Slab Semibold')
config.set('fonts.default_size', '10pt')
config.set('hints.chars', 'arstdhneio')
config.set('scrolling.smooth', True)

config.bind('n', 'scroll down')
config.bind('e', 'scroll up')
config.bind('i', 'scroll right')

config.bind('k', 'search-next')
config.bind('K', 'search-prev')
config.bind('s', 'enter-mode insert')
# Not necessary, but let's be clear that these things will no longer
# work.
for binding in ('sf', 'sk', 'sl', 'ss'):
    config.unbind(binding, mode='normal')

config.bind('H', 'tab-prev')
config.bind('I', 'tab-next')
config.bind('<Ctrl-o>', 'back')
config.bind('<Ctrl-i>', 'forward')

config.bind('gt', 'tab-next')
config.bind('gT', 'tab-prev')

config.bind('N', 'scroll down', mode='caret')
config.bind('E', 'scroll up', mode='caret')
config.bind('I', 'scroll right', mode='caret')
config.bind('n', 'move-to-next-line', mode='caret')
config.bind('e', 'move-to-prev-line', mode='caret')
config.bind('i', 'move-to-next-char', mode='caret')


def load_base16_colors():
    home = os.getenv("HOME")
    base16_dir = os.path.join(home, ".local", "share", "base16", "qutebrowser")

    shell_theme_file = os.path.join(home, ".base16_theme")

    if not os.path.islink(shell_theme_file):
        return

    real_theme_file = os.path.realpath(shell_theme_file)
    theme_name = os.path.splitext(os.path.basename(real_theme_file))[0]

    colors_config_file = os.path.join(
            base16_dir, "themes", "default",
            theme_name + ".config.py")

    config.source(colors_config_file)


load_base16_colors()
