#! /bin/sh

sxhkd &
$HOME/.config/polybar/start.sh

# Sets colors:
$HOME/.config/base16-hooks/20-bspwm.sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          40

bspc config top_padding    30
bspc config bottom_padding 30
bspc config right_padding  20
bspc config left_padding   20

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a dolphin-emu desktop='^9' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
